### ISSUE TITLE
Memory deallocation segmentation fault

### ISSUE THREAD

**Issue by leograba** [psaraci/risip#1]
Hi, 

I have compiled the risip-demo for ARM architecture and when the code runs, it breaks with a segmentation fault in the function RisipAccount::setConfiguration, called from Qt QML (Risip.accountForConfiguration(sipAccountDetails);) while trying to execute the following line in the risipaccount.cpp file:

`delete m_data->configuration;`

If I comment this line, the segmentation fault does not happen, but I get the following message from the application console:

```
QObject::disconnect: Unexpected null parameter
```

Do you have any advice how can I fix the "delete" issue? Is the QObject something to worry about?

Best regards

**Comment by kastravec** [comment]
Hi,

Thanks for reporting this, nothing critical to worry about. 
I’ll try to get this fixed asap. This is a problem with QML engine that sometimes is still referring to deleted objects from the c++ part. 
For now just comment it out, because anyway that object is being deleted already, or try calling deleteLater() , i.e. m_data->configuration->deleteLater() and see if that works...

Cheers,
Petref

**Comment by kastravec** [comment]
How are you creating the configuration on the QML side? Maybe you are not using the API property, meaning some calls have to be done in a specific order...there are many things undocumented 

Have you seen the risip demo app? Or the RisipApp? Should not experience the problem there.

**Comment by leograba** [comment]
Thank you very much for the help so far. Actually I'm trying to build the risip-demo app for ARM. I have cross-compiled PJSIP and tested using the pjsua command-line demo, then added the static libraries and headers to the risip platform and made some changes to the linuxplatform.pri file.

Now I see some more messages, but still have a segmentation fault error. When I run the application:

```
19:30:29.826   pjsua_core.c  .PJSUA state changed: STARTING --> RUNNING
CODEC INFO:  "PCMA/8000/1" "" 215
CODEC INFO:  "PCMU/8000/1" "" 214
CODEC INFO:  "GSM/8000/1" "" 128
CODEC INFO:  "iLBC/8000/1" "" 128
CODEC INFO:  "speex/32000/1" "" 0
CODEC INFO:  "speex/8000/1" "" 0
CODEC INFO:  "speex/16000/1" "" 0
CODEC INFO:  "G722/16000/1" "" 0
CODEC INFO:  "L16/44100/1" "" 0
CODEC INFO:  "L16/44100/2" "" 0
QObject::disconnect: Unexpected null parameter
SIP DEFAULT ACCOUNT  "sip:toptop@sip2sip.info"
19:30:29.830   pjsua_core.c  SIP UDP socket reachable at 192.168.0.12:53667
19:30:29.830   udp0x23e0488  SIP UDP transport started, published address is 192.168.0.12:53667
Segmentation fault (core dumped)
```

Then the issue was tracked to the login call from the risip-demo _Main.qml_:
`Risip.defaultAccount.login();`

And to the _risipaccount.cpp_ file:

```
        try {
            m_data->pjsipAccount->create(m_data->configuration->pjsipAccountConfig());
			qDebug() << "Bet it never gets here parssa 8";
        } catch (Error& err) {
			qDebug() << "Bet it never gets here parssa 9";
            setStatus(AccountError);
            setError(err);
            return;
        }
```

**Comment by kastravec** [comment]
No problem, great to see you using it in your project.
Others have also used my project for ARM, but not myself, i have only tested in all mobile and desktop platforms.

Anyway, first time i see a crash like this...can you share the backtrace of the crash? Or the debug trace just before crashing?

Also, when does it crash? Making a call? Registering the sip account?

Cheers
Petref

**Comment by leograba** [comment]
Hi Petref,

It crashes on login:

```
                //creating the account and setting as the default
                Risip.accountForConfiguration(sipAccountDetails);
                Risip.setDefaultAccount(sipAccountDetails.uri);

                //default account login
                Risip.defaultAccount.login();
```

I have found that this is the line where it breaks, from risipaccountconfiguration.cpp:

`m_data->accountConfig.sipConfig.proxies = { proxyUri.toStdString() }; //FIXME add proxy port`

I have to stop for today, but tomorrow will provide more information.

Best regards,
Leonardo

**Comment by leograba** [comment]
Hi Petref,

I have run using gdb and the backtrace is as follows:

Thread 1 "risip-demo" received signal SIGSEGV, Segmentation fault.
0x76f90308 in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
   from /usr/lib/libstdc++.so.6

---------------------------------------------------------------------------------------------------------

I have done some more testing:

Inside the function RisipAccountConfiguration::pjsipAccountConfig, from _risipaccountconfiguration.cpp_, I have tried to create a temporary account config and set the proxy:

```
AccountConfig tmpAccountConfig;
tmpAccountConfig.sipConfig.proxies.push_back(proxyUri.toStdString());
```

It gives the same segmentation fault error.

One test about adding to a vector of strings that works:

```
std::vector<std::string> myStringVector;
myStringVector.push_back(proxyUri.toStdString());
```

Best regards,
Leonardo

**Comment by kastravec** [comment]
Hi Leonardo,

Thanks for looking at this, i haven't seen any crash like this before on risip. 

The accountConfig.sipConfig.proxies is also just an array of strings ... std::vector<std::string>

Something is wrong maybe the crash happens somewhere else? In another thread? 

I will investigate on this during the weekend because unfortunately i do not have much time before that..

Is the crash happening on standard linux desktop? or windows/mac?

regards,
Petref

**Comment by leograba** [comment]
Hi Petref,

Thank you very much for your help, I will also look at it some more. Just FYI I was able to compile and make calls using this Qt solution/binding, therefore validating that the cross-compiled PJSIP libraries really work on the target ARM system:
https://www.metasec.de/voip-with-qt/

Best regards,
Leonardo
