### ISSUE TITLE
Risip Commercial License

### ISSUE THREAD

**Issue by Vloois** [psaraci/risip#5]
Hi, 

Can you please provide contact information in order for me to inquire about the possibility and pricing of a commercial license? 

Thank you, and keep up the good work.

**Comment by kastravec** [comment]
Hi,

Sure, drop me a line at psaraci@gmail.com .

The license fee to convert Risip to commercial is insignificant, I can help you with that.

cheers,
Petref

**Comment by Vloois** [comment]
Hi Petref, 

Thank you very much, I have sent you a mail, please also check your spam in case you haven't seen it. 

Regards,

**Comment by kastravec** [comment]
Hi,

Yes, received the email and just replied. Unfortunately it was in spam and had to look it up there.. I'm sorry for any delays.

Thanks,
Petref
